### ISSUE TITLE
Release 0.4.7 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1442]
This issue is used to organize the version 0.4.7 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| April 9th 2017, 4pm    | Create release branch from master |
| April 13th 2017, 12 noon     | Release Candidate 1               |
| ~~April 21st 2017, 10am~~     | **POSTPONED** Release Candidate 2               |
| April 24th 2017, 5pm     | Release Candidate 2               |
| ~~April 27th 2017~~     | **POSTPONED** Declaring Release                 |
| May 1st 2017     | Declaring Release                 |

*All times are UTC.*

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Create release branch from development branch master by using:
```
git checkout -b release-0.4.7 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.7`, remove trailing `+` if needed.
* [x] *On release branch HEAD* - Remove `Super Testers` species.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.7+`.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release Candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.7 Release Candidate 1"  v0.4.7-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce availability of release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release Candidate 2

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.7 Release Candidate 2"  v0.4.7-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate by using:
```
git tag --annotate --message="0.4.7 Stable Release"  v0.4.7
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [x] Prune release candidate tags.
* [x] Prune release branch.

### Blocking issues and pull requests

[Issues and PRs blocking v0.4.7](https://github.com/freeorion/freeorion/milestone/16)

**Comment by Vezzra** [comment]
***Update:***

* Stated the deadlines for creation of the release branch and RC1 more precisely by adding exact times to the dates.
* Changed the date format.

**Comment by geoffthemedio** [comment]
Initial changelog update: https://github.com/freeorion/freeorion/commit/5329c7a468699178d34aa8add5a049a88a330e0d

**Comment by Ouaz** [comment]
@Vezzra 

For the 0.4.6 release, you had adjusted the default font size (decrease) only on the release branch, because the actual sizes (16 and 17) don't look good (too big) on Mac (whereas it's OK on Windows) -> 06d027f

AFAIK, the font size difference between Mac and Windows versions has not been fixed.

Just a reminder if you forgot it. ^^

**Comment by Vezzra** [comment]
Ah yes, thanks, have completely forgotten about that.

Just committed a stop-gap fix to master (a55b0cf9ee566777f97f114b3a2e73d68216d258) which uses the slightly reduced default font sizes on OSX, that should take care of the issue until we come up with something better.

**Comment by Vezzra** [comment]
***Update:*** checked completed items.

**Comment by Vezzra** [comment]
***Update***: Release Candidate 1 is out.

**Comment by Vezzra** [comment]
***Update:*** Added milestone and checklist for Release Candidate 2.

**Comment by Ouaz** [comment]
@Vezzra

To no give you useless extra work, I will update the FR stringtables only with en.txt commits tagged as "cherry_pick for release" or already cherry-picked.

So, each new commit for the FR stringtables (once per week -as usual-, until the final release build) can be safely cherry-picked (indicated in the commit title and commented with your ID, so you will get a notification)

Example:   latest fr.txt commit -> 8548a93

**Comment by Vezzra** [comment]
Thanks, that certainly makes things a lot easier. If you could throw in an extra pass (aside from the usual weekly one) on updating the French stringtable right before I make a new release candidate (the next one currently scheduled for Friday, see above), that would be perfect (of course only if it's necessary). 😃

**Comment by Vezzra** [comment]
***Update:*** Postponed deadlines for Release Candidate 2 and Declaring Release.

**Comment by Vezzra** [comment]
***Update***: Release Candidate 2 is out.

**Comment by Vezzra** [comment]
***Update:*** Declared RC2 as the stable 0.4.7 release.
