### ISSUE TITLE
Bugfix Release 0.4.7.1 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1686]
### Milestones

Important milestones for the bugfix release.  Changes will be announced by the release manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| 2017-08-20     | Recreate release branch from `v0.4.7` tag |
| 2017-08-24     | Release Candidate 1               |
| ~2017-09-03~     | POSTPONED ~Declaring Release~                 |
| 2017-09-03     | Release Candidate 2               |
| 2017-09-10     | Declaring Release               |

*All times are UTC.*

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Recreate release branch from `v0.4.7` tag.
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.7.1`.
* [x] Push updated release branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Cherry pick bugfix commits which have been accepted for inclusion into the
      bugfix release into the release branch.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.7.1 Release Candidate 1"  v0.4.7.1-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce availability of release candidates in `News` section
      of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 2

* [x] Cherry pick bugfix commits which have been accepted for inclusion into the
      bugfix release into the release branch.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.7.1 Release Candidate 2"  v0.4.7.1-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.4.7.1 Stable Release"  v0.4.7.1
```
* [x] Push release tag to GitHub.
* [x] Write description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [x] Prune release candidate tags.
* [x] Prune release branch.
