### ISSUE TITLE
Release 0.4.8 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2111]
This issue is used to organize the version 0.4.8 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| May 20th 2018, 6pm | Create release branch from master |
| June 14th, 1pm | Release Candidate 1               |
| July 13th, 1pm | Release Candidate 2               |
| ~~July 19th, 1pm~~ | ~~Release Candidate 3~~               |
| August 23rd 2018, 1pm | Release Candidate 3               |
| ~~June 28th, 1pm~~ | ~~Declaring Release~~                 |
| ~~July 22nd, 1pm~~ | ~~Declaring Release~~                 |
| ~~July 23rd, 1pm~~ | ~~Declaring Release~~                 |
| August 30th 2018, 1pm | Declaring Release                 |

*All times are UTC.*

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions.
* [x] Determine initial milestones and dates for release.
* [x] Create release branch from development branch master by using:
```
git checkout -b release-v0.4.8 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.8`, remove trailing `+` if needed.
* [x] *On release branch HEAD* - Disable `Super Testers` species by default.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.8+`.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.8 Release Candidate 1" v0.4.8-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce availability of release candidates in `News` section
       of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 2

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.8 Release Candidate 2" v0.4.8-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 3

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.8 Release Candidate 3" v0.4.8-rc3
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.4.8 Stable Release" v0.4.8
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [x] Prune release candidate tags.
* [ ] Prune release branch.

### Blocking issues

[Issues and PRs blocking v0.4.8](https://github.com/freeorion/freeorion/milestone/18)

**Comment by Vezzra** [comment]
As this is purely an "administrative"/"management" issue, basically a checklist for the release procedure, assigning this to a milestone (especially the mandatory milestone, as this issue doesn't block anything), doesn't make much sense.

**Comment by Vezzra** [comment]
Milestones have been updated.

**Comment by Vezzra** [comment]
Milestones have been updated.
Section for RC3 has been added.

**Comment by Vezzra** [comment]
Milestones have been updated.

**Comment by Vezzra** [comment]
Milestones have been updated.

**Comment by Vezzra** [comment]
RC3 has been released, checklist updated accordingly.

**Comment by Vezzra** [comment]
0.4.8 has been released, checklist items updated accordingly.
