### ISSUE TITLE
Allow player to disconnect from the server without stopping the game

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2243]
### Description

Current architecture doesn't support disconnected player:

1. `PlayerInfo` is sent based on connected players. If someone disconnected on turn change he won't be included in players' list even with active empire.
1. `ServerSaveGameDataRequestMessage` requested from connected players and saved on `ClientSaveData` response. If someone disconnected on turn change he won't be included in save.
    * `PlayerSaveHeaderData` also have information about client type of connected player.
1. The server stops game on any player has disconnected.

First two of them require to change client-server interaction. Third could be implemented quickly but depends on previous issues:

- [x] Change player list so it will be empire-based not player-based. Also it should include Observers and Moderators without empires (#2347).
- [x] Change messages with `PlayerStatus` to make them empire-based not player-based (#2352).
- [x] Send `ClientSaveData` with turn orders and remember them until save (#2364).
- [x] There should be an option to manage conditions when the server stops or continue game with disconnected player (#2379).
- [x] Allow to load saved game without all players (#2400).
- Here will be possible to launch 'longturn' server.
- [x] Allow to save games with partial orders and readiness status so players won't be required to have game continuously running to make a turn (#2404). 

Forum thread: https://freeorion.org/forum/viewtopic.php?f=28&t=11080

### Expected Result
Player will be allowed to make turn orders, disconnect and then continue the game without stopping the game for other players.

**Comment by Dilvish-fo** [comment]
Just to explicitly point out, I think that the "manage conditions" part should include that for a single player game,disconnecting ___does___ cause the server to terminate.

**Comment by dbenage-cx** [comment]
> for a single player game,disconnecting does cause the server to terminate.

Might not be always wanted for external server.

Maybe a server startup option pointing to the monitored client(s)?
For a normal single player game, we just change human client to start server with new option.
Multiplayer could then be any number of specific players and/or some dummy "observer" for connection monitoring.

**Comment by o01eg** [comment]
> Just to explicitly point out, I think that the "manage conditions" part should include that for a single player game,disconnecting does cause the server to terminate.

I suppose single-player game doesn't need to continue game on disconnection.

> Might not be always wanted for external server.
> Maybe a server startup option pointing to the monitored client(s)?

What about host player?

**Comment by dbenage-cx** [comment]
My thought is, who should be host with an external/headless server. There may be multiple local clients, or the owner of a server may wish to temporary use a local client.

When testing local "external server", a minor inconvenience is needing to restart the server after each client exit. This can start to chaff when troubleshooting an intermittent issue.

None of that is a typical user concern, so they are minor requests.

**Comment by o01eg** [comment]
@geoffthemedio Is hostless mode not enough for it?

**Comment by geoffthemedio** [comment]
@o01eg Probably in most cases, actually...
