### ISSUE TITLE
Release 0.4.9 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2656]
This issue is used to organize the version 0.4.9 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| Nov 24th 2019, 1pm     | Create release branch from master |
| **POSTPONED** ~~Dec 3rd 2019, 6pm~~     | ~~Release Candidate 1~~               |
| **POSTPONED** ~~Dec 16th 2019, 6pm~~     | ~~Release Candidate 1~~               |
| **POSTPONED** ~~Dec 22nd 2019, 1pm~~     | ~~Release Candidate 1~~               |
| Jan 13th 2020, 3pm     | Release Candidate 1               |
| **POSTPONED** ~~Jan 26th 2020, 2pm~~    | ~~Declaring Release~~                 |
| Jan 26th 2020, 2pm    | Release Candidate 2                 |
| **POSTPONED** ~~Feb 2nd 2020, 2pm~~    | ~~Declaring Release~~                 |
| Feb 2nd 2020, 2pm    | Release Candidate 3                 |
| Feb 9th 2020, 2pm    | Declaring Release                 |

*All times are UTC.*

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Create release branch from development branch master by using:
```
git checkout -b release-v0.4.9 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.9`, remove trailing `+` if needed.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.9+`.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.9 Release Candidate 1"  v0.4.9-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 2

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.9 Release Candidate 2"  v0.4.9-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 3

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.9 Release Candidate 3"  v0.4.9-rc3
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.4.9 Stable Release"  v0.4.9
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [x] Prune release candidate tags.
* [x] Prune release branch.

### Blocking issues

[Issues blocking v0.4.9](https://github.com/freeorion/freeorion/issues?q=is%3Aopen+milestone%3A%22v0.4.9%22)

**Comment by geoffthemedio** [comment]
Should you add making super testers default disabled a task as well? I thought that would happen automatically now, but apparently not...?

**Comment by Vezzra** [comment]
If the consensus is that Super Testers should stay enabled by default in master, then yes, adding a task for setting that game rule do default off in the release branch makes sense.

I think I'm going to do that right now. Better safe than sorry... 😉

**Comment by Vezzra** [comment]
...aaaand when I did that, I just saw that there *already is* a task for that, which I obviously completely missed when I created the release branch for 0.4.9. Must have been in some kind of stupor... I'll try to pay attention better next time... 🙄

**Comment by Vezzra** [comment]
Well, that task isn't there in the above list... hm, maybe I accidentally deleted it when I created the issue?!?! Dunno what went wrong here, but shouldn't happen again...
