### ISSUE TITLE
Release 0.4.10 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2980]
This issue is used to organize the version 0.4.10 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| May 24th 2020 UTC    | Create release branch from master |
| **POSTPONED** ~~July 9th 2020, 3pm UTC~~    | Release Candidate 1               |
| July 10th 2020, 10am UTC    | Release Candidate 1               |
| July 26th 2020 UTC     | Declaring Release                 |

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Create release branch from development branch master by using:
```
git checkout -b release-v0.4.10 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.10`, remove trailing `+` if needed.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.10+`.
* [x] *On release branch HEAD* - Disable `Super Testers` species by default.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.10 Release Candidate 1"  v0.4.10-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.4.10 Stable Release"  v0.4.10
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [ ] Prune release candidate tags.
* [ ] Prune release branch.

### Blocking issues and PRs

[Issues and PRs blocking v0.4.10](https://github.com/freeorion/freeorion/issues?q=is%3Aopen+milestone%3A%22v0.4.10%22)

**Comment by adrianbroher** [comment]
Because I just stumbled of an instance:  Did you disable supertesters yet?

**Comment by geoffthemedio** [comment]
> Because I just stumbled of an instance: Did you disable supertesters yet?

` On release branch HEAD - Disable Super Testers species by default.` is checked above and:

https://github.com/freeorion/freeorion/commit/c132c36b07ffb52e72df49160142409a7e17ae0d#diff-2c72f469f6eb4a33f8df9a20f7bd674e

**Comment by Vezzra** [comment]
Yep, after getting it wrong last time, I specifically paid attention not to make the same mistake again...
