### ISSUE TITLE
Tracking issue for Python FOCS migration

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3372]
Feature request
===============

Idea
----

Use Python as language for content scripting which generates in-game structures while execution

Gain
----

Less compile time for parsers. Better error messages.

Discussion
----------

https://freeorion.org/forum/viewtopic.php?f=9&t=10215

Preparation ready PRs:

- [x] https://github.com/freeorion/freeorion/pull/3371 - Need to ensure all game techs are parsed. Could be merged to `master` as it doesn't introduce new parser.
- [x] https://github.com/freeorion/freeorion/pull/3342 - Need to have python available in common library and client. Could be merged to `master` as it doesn't introduce new parser. Also it uses already existing python dependency. 
- [x] https://github.com/freeorion/freeorion/pull/3379 - Introduces background thread for parsing to don't have to deal with python GIL. Could be merged to `master` as it doesn't introduce new parser.

Mandatory parser PRs:

- [x] https://github.com/freeorion/freeorion/pull/3211 - Introducing python parser
- [x] https://github.com/freeorion/freeorion/pull/3265 - Parse game rules
- [x] https://github.com/freeorion/freeorion/pull/3373 - Parse techs categories
- [x] https://github.com/freeorion/freeorion/pull/3309 - Parse techs in parallel with FOCS parser. Here migration could be started.
- [x] https://github.com/freeorion/freeorion/pull/3568 - Parse on Android

Leftover parser PRs:

- [x] Parse remaining techs
- [x] Parse species (tests, parallel, remaining)
- [x] Parse buildings (tests, parallel, remaining)
- [x] Parse empire statistics (tests, all)
- [x] Parse encyclopedia (tests, parallel, remaining)
- [x] Parse fields (tests, all)
- [ ] Parse named values (tests, parallel, remaining)
- [ ] Parse monster designs (tests, parallel, remaining)
- [ ] Parse policies (tests, parallel, remaining)
- [ ] Parse ship designs (tests, parallel, remaining)
- [ ] Parse ship hulls (tests, parallel, remaining)
- [ ] Parse ship parts (tests, parallel, remaining)
- [ ] Parse specials (tests, parallel, remaining)
- [ ] Parse starting unlocks (tests, all)
- [ ] Parse monster fleet (tests, all)
- [ ] Switch from globals to modules
- [ ] Typing in modules
- [ ] Docstrings for modules

**Comment by agrrr3** [comment]
If the following is both true we should disable the named value lookup retries, because it only generates delay without any hope of finding the named value (because no other parsing is happening anymore). I tried locally a recursive named lookup and the resulting delays were ridiculous.
* all contents gets build via the python parser
* the python parser is single-threaded

Related to issue #3225

**Comment by o01eg** [comment]
@agrrr3 The first isn't yet achieved.
