### ISSUE TITLE
Release 0.4.10.2 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#3533]
This issue is used to organize the version 0.4.10.2 maintenance release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| Aug 1st 2021 | Release Candidate 1               |
| Aug 15th 2021 | Declaring Release                 |

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Update `packaging/org.freeorion.FreeOrion.metainfo.xml` and linked screenshots if necessary
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.4.10.2`, remove trailing `+` if needed.
* [x] Push updated release branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.4.10.2 Release Candidate 1"  v0.4.10.2-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.4.10.2 Stable Release"  v0.4.10.2
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [ ] Prune release candidate tags.
* [ ] Prune release branch.

### Blocking issues

[Issues blocking v0.4.10.2](https://github.com/freeorion/freeorion/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v0.4.10.2%22)
