### ISSUE TITLE
Release 0.5 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#4320]
This issue is used to organize the version 0.5 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| 2022-11-13 | Create release branch from master |
| 2023-02-16 | Release Candidate 1               |
| 2023-03-07 | Release Candidate 2               |
| 2023-03-21 | Release Candidate 3               |
| 2023-04-02 | Declaring Release                 |

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue from `.github/RELEASE_TEMPLATE.md` and follow
      instructions.
* [x] Determine initial milestones and dates for release.
* [x] Update `packaging/org.freeorion.FreeOrion.metainfo.xml` and linked screenshots if necessary
* [x] Merge PR #3977 into master
* [x] Create release branch from development branch master by using:
```
git checkout -b release-v0.5 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.5`, remove trailing `+` if needed.
* [x] *On release branch HEAD* - Disable `Super Testers` species by default.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.5+`.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5 Release Candidate 1"  v0.5-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 2

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5 Release Candidate 2"  v0.5-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 3

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5 Release Candidate 3"  v0.5-rc3
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.5 Stable Release"  v0.5
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master. 
* [x] Prune release candidate tags.
* [x] Prune release branch.

### Blocking issues and PRs

[Issues and PRs blocking v0.5](https://github.com/freeorion/freeorion/milestone/26)

**Comment by o01eg** [comment]
To not forget also merge https://github.com/freeorion/freeorion/pull/4295 to release branch after split.

**Comment by Vezzra** [comment]
Ok. I can't change your PR to be set against the release branch instead of master (or at least I don't know how to do that), so I will simply take your `revert-species-parser` branch and merge that directly via git into the release branch.

**Comment by o01eg** [comment]
@Vezzra I can edit PR and choose other branch.

**Comment by Vezzra** [comment]
Ok, I'll notify you after the release branch has been created, then you can do it yourself.
