### ISSUE TITLE
Release 0.5.1 preparation

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#5032]
This issue is used to organize the version 0.5.1 release of FreeOrion.

### Milestones

Important milestones for the release.  Changes will be announced by the release
manager.

| Date             | Milestone                         |
|:---------------- | --------------------------------- |
| 2024-11-17     | Create release branch from master |
| 2024-12-04     | Release Candidate 1               |
| 2024-12-24     | Release Candidate 2               |
| 2025-01-21     | Release Candidate 3               |
| ~~2024-12-15~~     | **POSTPONED** Declaring Release                 |
| ~~2025-01-31~~     | **POSTPONED** Declaring Release                 |
| ~~2025-02-02~~     | **POSTPONED** Declaring Release                 |
| 2025-02-02     | Release Candidate 4               |
| 2025-02-07     |  Declaring Release                 |

### Checklist

This is a checklist for the release manager to ensure all steps are done before
doing the actual release.

#### Preparations

* [x] Create a new GitHub Issue using `Publish release` template and follow
      instructions. :wink:
* [x] Determine initial milestones and dates for release.
* [x] Add the new release in `packaging/org.freeorion.FreeOrion.metainfo.xml`
* [x] Update the screenshots in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] Create release branch from development branch master by using:
```
git checkout -b release-v0.5.1 master
```
* [x] *On release branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.5.1`, remove trailing `+` if needed.
* [x] *On release branch HEAD* - Disable `Super Testers` species by default.
* [x] *On master branch HEAD* - Update version number in `CMakeLists.txt` and
      `cmake/make_versioncpp.py` to `v0.5.1+`.
* [x] Push updated release and master branch to GitHub.
* [x] Update `ChangeLog.md`.

#### Release candidate 1

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] Update the release date in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] Update the screenshots in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5.1 Release Candidate 1"  v0.5.1-rc1
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] If this is the first release candidate, announce availability of
      release candidates in `News` section of FreeOrion Wiki.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 2

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] Update the release date in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] Update the screenshots in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5.1 Release Candidate 2"  v0.5.1-rc2
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 3

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] Update the release date in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] Update the screenshots in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5.1 Release Candidate 3"  v0.5.1-rc3
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Release candidate 4

* [x] Integrate incoming bugfixes.
* [x] Update `ChangeLog.md` again if needed.
* [x] Update the release date in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] Update the screenshots in `packaging/org.freeorion.FreeOrion.metainfo.xml` if necessary
* [x] *On release branch HEAD* - Tag the release candidate by using:
```
git tag --annotate --message="0.5.1 Release Candidate 4"  v0.5.1-rc4
```
* [x] Push release candidate tag to GitHub.
* [x] Build release candidate artifacts.
* [x] Upload release candidate artifacts to SourceForge.
* [x] Announce release candidate on Twitter as @FreeOrion
* [x] Test release candidate.

#### Declare release

* [x] Determine if another release candidate is needed or if the latest release
      candidate is ready to be declared as the official stable release.
* [x] *On release branch* - Tag the release from the latest release candidate
       by using:
```
git tag --annotate --message="0.5.1 Stable Release"  v0.5.1
```
* [x] Push release tag to GitHub.
* [x] Write `Key Changes` description for GitHub releases page.
* [x] Upload release artifacts to GitHub.
* [x] Announce release in `News` section of FreeOrion Wiki.
* [x] Update `Main` page of FreeOrion Wiki.
* [x] Update `Download` page of FreeOrion Wiki.
* [x] Announce release on Twitter as @FreeOrion
* [x] Announce release on YouTube.

#### Cleanup

* [x] Cherry-pick updates of `ChangeLog.md` to master.
* [ ] Prune release candidate tags.
* [ ] Prune release branch.

### Blocking Issues and PRs

[Issues and PRs blocking v0.5.1](https://github.com/freeorion/freeorion/milestone/29)

**Comment by travier** [comment]
For folks that want to give the RC a try on Linux, I've pushed the 0.5.1-rc1 to Flathub's Beta repo:
- https://github.com/flathub/org.freeorion.FreeOrion/tree/beta
- https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

Currently still building but should be up soon.
